environments:
  development:
    pipelines:
      - activesupport-fiscal_dates
pipelines:
  activesupport-fiscal_dates:
    group: development
    materials:
      gitMaterial1:
        git: git@github.com:kinesisptyltd/activesupport-fiscal_dates.git
    stages:
      - test:
          jobs:
            rspec:
              artifacts:
                - test:
                    source: junit.xml
                    destination: junit
              tasks:
                - exec:
                    command: squirrel
                    arguments:
                    - restore
                    - Gemfile.lock
                - exec:
                    command: bundle
                    arguments:
                    - install
                    - --path
                    - vendor/gems
                - exec:
                    command: squirrel
                    arguments:
                    - cache
                    - Gemfile.lock
                    - vendor/gems
                - exec:
                    command: bash
                    arguments:
                    - -c
                    - bundle exec rspec spec --no-fail-fast -r rspec_junit_formatter --format RspecJunitFormatter -o junit.xml
